// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelTask(arg1) {
  return window['go']['backend']['App']['CancelTask'](arg1);
}

export function GetFFmpegVersion() {
  return window['go']['backend']['App']['GetFFmpegVersion']();
}

export function GetTaskStatus(arg1) {
  return window['go']['backend']['App']['GetTaskStatus'](arg1);
}

export function ListTasks() {
  return window['go']['backend']['App']['ListTasks']();
}

export function SelectDirectory() {
  return window['go']['backend']['App']['SelectDirectory']();
}

export function SelectFile() {
  return window['go']['backend']['App']['SelectFile']();
}

export function StartTask(arg1) {
  return window['go']['backend']['App']['StartTask'](arg1);
}
