// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function CancelTask(arg1:string):Promise<void>;

export function GetFFmpegVersion():Promise<string>;

export function GetTaskStatus(arg1:string):Promise<backend.Task>;

export function ListTasks():Promise<Array<backend.Task>>;

export function SelectDirectory():Promise<string>;

export function SelectFile():Promise<string>;

export function StartTask(arg1:string):Promise<backend.Task>;
